name: Auto Merge Pull Requests

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Wait for 20 seconds
        run: sleep 20

      - name: Auto-merge the PR
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash   # or "merge" / "rebase" if you prefer
          MERGE_COMMIT_MESSAGE: "Auto-merged by GitHub Action"
